con nn.module puedo crear mi propia capa o un módulo que puedo reutilizar en varias capas

In [5]:
import torch
import torch.nn as nn

In [6]:
class myLayer(nn.Module):
    def __init__(self,size_in):
        super().__init__()
        self.size = size_in
        #quiero que mi capa haga [1,2]*[2,2]=[2,4] pero tengo que actualizar pesos, así lo hago:
        weight = torch.Tensor(self.size)
        self.weight = nn.Parameter(weight)
        # si ahgo esto self.weight = weight no se actualizan los pesos
        # inicializacion normal
        torch.nn.init.normal_(self.weight, mean=0.0, std=1.0)
        
    def forward(self,x):
        return x * self.weight

In [7]:
#instancia de la capa
a = myLayer(10)

In [8]:
a.weight

Parameter containing:
tensor([ 2.0050, -1.5120, -0.4189, -1.5013, -0.6047,  1.0192,  0.6854, -0.3820,
         0.1315, -2.7018], requires_grad=True)

In [9]:
#como pueda usar esta capa en otro modulo?
myNetwork = nn.Sequential(
    myLayer(10),
    nn.ReLU()
)

In [10]:
myNetwork

Sequential(
  (0): myLayer()
  (1): ReLU()
)

In [11]:
input = torch.ones([1,10])
myNetwork(input)

tensor([[0.0000, 0.7524, 0.0575, 0.0000, 0.3424, 0.2247, 0.0000, 0.2200, 0.3546,
         0.3323]], grad_fn=<ReluBackward0>)

In [13]:
#le puse el 2 y ahora tengo 2 copias de la capa
input = torch.ones([2,10])
myNetwork(input)

tensor([[0.0000, 0.7524, 0.0575, 0.0000, 0.3424, 0.2247, 0.0000, 0.2200, 0.3546,
         0.3323],
        [0.0000, 0.7524, 0.0575, 0.0000, 0.3424, 0.2247, 0.0000, 0.2200, 0.3546,
         0.3323]], grad_fn=<ReluBackward0>)