In [33]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 --quiet

In [34]:
import torch as pt

In [35]:
pt.__version__

'2.2.1'

In [36]:
#Long tensor
a=pt.tensor([[1,2],[3,4]])

In [37]:
a

tensor([[1, 2],
        [3, 4]])

In [38]:
a.shape

torch.Size([2, 2])

In [39]:
a.type()

'torch.LongTensor'

In [40]:
#Float tensor
b=pt.tensor([[1,2],[3,4]],dtype=pt.float32)

In [41]:
b.type()

'torch.FloatTensor'

In [42]:
#Double tensor
c=pt.tensor([[1,2],[3,4]],dtype=pt.float64)

In [43]:
c.type()

'torch.DoubleTensor'

In [44]:
#Half tensor
d=pt.tensor([[1,2],[3,4]],dtype=pt.float16)

In [45]:
d.type()

'torch.HalfTensor'

In [46]:
#se pueden hacer operaciones aritméticas normales
a*2

tensor([[2, 4],
        [6, 8]])

In [49]:
#si quisiera aplanar el tensor original debería hacer
# a=a.flatten()
a.flatten()

tensor([1, 2, 3, 4])

In [48]:
a

tensor([[1, 2],
        [3, 4]])

In [53]:
# mi tensor anterior tenía una dimension de 2x2 ahora es de 4x1
b=a.reshape([1,1,2,2])

In [54]:
b.shape

torch.Size([1, 1, 2, 2])

In [55]:
#podría no especificar todos los elementos del reshape
b=a.reshape([1,1,-1,2])

In [56]:
b.shape

torch.Size([1, 1, 2, 2])

In [57]:
b

tensor([[[[1, 2],
          [3, 4]]]])

In [58]:
#Referirme a elementos del tensor
b[0]

tensor([[[1, 2],
         [3, 4]]])

In [59]:
b[0][0]

tensor([[1, 2],
        [3, 4]])

In [60]:
b[0][0][0]

tensor([1, 2])

In [61]:
b[0][0][0][0]
# b[0,0,0,0]

tensor(1)

In [62]:
a[0,0]

tensor(1)

In [63]:
#es otra forma de hacer reshape
a.view([1,-1])


tensor([[1, 2, 3, 4]])

In [64]:
a

tensor([[1, 2],
        [3, 4]])

## Segunda parte

In [65]:
def compute():
    #si quiero tener en cuenta los gradientes de un tensor
    a=pt.tensor([3.],requieres_grad=True)
    o=5*a**2
    return [a,o]


In [ ]:
[a,o]=compute()
print(a)
print(o)