In [21]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 --quiet

In [22]:

import torch
from torch import nn
from torch.nn import functional as F


In [23]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.l1 = nn.Linear(1, 10)
        self.l2 = nn.Linear(10, 1)

    #define como los datos fluyen por la red
    def forward(self, x):
        x = self.l1(x)
        x = F.relu(x)
        x = self.l2(x)
        return x

In [24]:
model = Model()
model

Model(
  (l1): Linear(in_features=1, out_features=10, bias=True)
  (l2): Linear(in_features=10, out_features=1, bias=True)
)

In [25]:
a= torch.tensor([5.])
model(a)

tensor([0.7457], grad_fn=<ViewBackward0>)

In [26]:
# me da una lista de los pesos que tengo
model.state_dict()

OrderedDict([('l1.weight',
              tensor([[ 0.4079],
                      [ 0.3886],
                      [-0.1713],
                      [-0.4757],
                      [ 0.8856],
                      [ 0.6163],
                      [ 0.8054],
                      [-0.1101],
                      [-0.1766],
                      [-0.0763]])),
             ('l1.bias',
              tensor([-0.3100,  0.4757,  0.1178,  0.7440,  0.8539, -0.7888, -0.5948, -0.2162,
                       0.7705, -0.9273])),
             ('l2.weight',
              tensor([[ 0.1366, -0.0160,  0.0092, -0.1517,  0.1603,  0.1131, -0.2209, -0.0972,
                       -0.2121,  0.0736]])),
             ('l2.bias', tensor([0.2007]))])

In [27]:
#parametros presentes
model.named_parameters

<bound method Module.named_parameters of Model(
  (l1): Linear(in_features=1, out_features=10, bias=True)
  (l2): Linear(in_features=10, out_features=1, bias=True)
)>

In [28]:
for i in model.named_parameters():
    print(i)

('l1.weight', Parameter containing:
tensor([[ 0.4079],
        [ 0.3886],
        [-0.1713],
        [-0.4757],
        [ 0.8856],
        [ 0.6163],
        [ 0.8054],
        [-0.1101],
        [-0.1766],
        [-0.0763]], requires_grad=True))
('l1.bias', Parameter containing:
tensor([-0.3100,  0.4757,  0.1178,  0.7440,  0.8539, -0.7888, -0.5948, -0.2162,
         0.7705, -0.9273], requires_grad=True))
('l2.weight', Parameter containing:
tensor([[ 0.1366, -0.0160,  0.0092, -0.1517,  0.1603,  0.1131, -0.2209, -0.0972,
         -0.2121,  0.0736]], requires_grad=True))
('l2.bias', Parameter containing:
tensor([0.2007], requires_grad=True))


In [29]:
a= torch.ones([10,1])
model.l1.weight = torch.nn.Parameter(a)
model.l1.weight

Parameter containing:
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]], requires_grad=True)

In [30]:
#para correrlo en gpu
#model.to('cuda:0')
#para correr en cpu
model.to('cpu')

Model(
  (l1): Linear(in_features=1, out_features=10, bias=True)
  (l2): Linear(in_features=10, out_features=1, bias=True)
)

In [31]:
a= torch.tensor([5.])
model(a)

tensor([-1.0189], grad_fn=<ViewBackward0>)

In [32]:
# puedo evaluar mi red de dos formas:
# model.eval() hace que la red se comporte como si estuviera en modo de evaluación
model.eval()
print(model(a))
# model.train() hace que la red se comporte como si estuviera en modo de entrenamiento
with torch.no_grad():
    print(model(a))

tensor([-1.0189], grad_fn=<ViewBackward0>)
tensor([-1.0189])


In [33]:
model.zero_grad()